sonar.projectKey=ai-sprint-backend
sonar.organization=datics-ai
sonar.projectName=AI Sprint Backend

sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/generated/**

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.qualitygate.wait=true
